

## 响应体消息多语言国际化，默认zh（简体中文）
## 2025-09-16 05:20:00 -- vx: 18888461290  SHENZHEN.GUANGDONG.CHINA

[video_not_found]
zh = "哇！这个视频不见了！" ## 汉语
en = "Oops! This video is missing!"  ## 英语
ja = "おっと！この動画は見つかりません！" ## 日语
ko = "앗! 이 동영상을 찾을 수 없습니다!"  ## 韩语
vi = "Ôi! Video này không tìm thấy!" ## 越南语
th = "โอ๊ะ! ไม่พบวิดีโอนี้!" ## 泰语
fr = "Oups ! Cette vidéo est introuvable !" ## 法语
de = "Hoppla! Dieses Video wurde nicht gefunden!" ## 德语


[user_not_found]
zh = "哇！这个用户不见了！" ## 汉语
en = "Oops! This user is missing!"  ## 英语
ja = "おっと！この動画は見つかりません！" ## 日语
ko = "앗! 이 동영상을 찾을 수 없습니다!"  ## 韩语
vi = "Ôi! Video này không tìm thấy!" ## 越南语
th = "โอ๊ะ! ไม่พบวิดีโอนี้!" ## 泰语
fr = "Oups ! Cette vidéo est introuvable !" ## 法语
de = "Hoppla! Dieses Video wurde nicht gefunden!" ## 德语