##### gate_http/src/cargo.toml
## HTTP 网关

[package]
name = "gate_http"
version = "0.1.0"
edition = "2024"

[dependencies]
## 本地依赖
cola_auth = { path = "../cola_auth" } # 可乐验证中心
# cola_three = { path = "../cola_three" } # 可乐基础
cola_dynamic = { path = "../cola_dynamic" } # 可乐动态
cola_gis = { path = "../cola_gis" } # 可乐GIS
cola_live = { path = "../cola_live" } # 可乐直播
cola_music = { path = "../cola_music" } # 可乐短视频
cola_three = { path = "../cola_three" } # 可乐第三方
cola_video = { path = "../cola_video" } # 可乐短视频
cola_user = { path = "../cola_user" } # 可乐用户中心
app_config = { path = "../app" } # APP配置
cola_data = { path = "../cola_data" } # 数据中心
port = { path = "../port" } # 服务端口
network = { path = "../network" }


## 外部依赖
actix-web = "4.14.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = "1.47.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
chrono = { version = "0.4.44", features = ["serde"] }
uuid = { version = "1.20.0", features = ["v4"] }
anyhow = "1.0.99"
once_cell = "1.21.3"
futures-util = "0.3.31"
# 建议选这个，它是纯 Rust 实现，兼容性最好，编译最省事
jsonwebtoken = { version = "10", features = ["rust_crypto"] }

