#### 可乐短视频后端服务器
# 2025-12-10 12:01

[package]
name = "short-video"
version = "0.1.0"
edition = "2024"

#### 工作区
[workspace]
members = ["gate_http", "cola_video", "app", "gate_grpc", "health", "cola_infra", "im", "repository", "cola_data", "cola_dynamic", "cola_gis", "kits", "cola_user", "cola_music", "cola_auth", "cola_live", "cola_fs", "cola_im", "cola_three", "repo_adapter", "service", "port", ]

[workspace.package]
version = "0.1.0"
edition = "2024"

#### 外部依赖
[dependencies]
futures = "0.3.31"
tokio = { version = "1.47.0", features = ["full"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

#### 内部依赖
# HTTP 网关
gate_http = { path = "./gate_http" }
# GRPC 网关
gate_grpc = { path = "./gate_grpc" }
# DATA 数据
cola_data = { path = "./cola_data" }
# 应用配置
app_config = { path = "./app" }
# 应用健康
health = { path = "./health" }
# 外部网络
cola_infra = { path = "./cola_infra" }
# 消息服务
im = { path = "im" }

# 业务模块
cola_auth = { path = "cola_auth" }
cola_dynamic = { path = "cola_dynamic" }
cola_live = { path = "cola_live" }
cola_music = { path = "cola_music" }
cola_video = { path = "cola_video" }
cola_user = { path = "cola_user" }

# 适配器层
repo_adapter = { path = "./repo_adapter" }

# 构建优化（发行版）
[profile.release]
debug = true             # DEBUG模式
lto = true               # 链接时优化（提升性能）
codegen-units = 1        # 单代码生成单元（提升优化效果）
opt-level = 3            # 最高优化级别
strip = true             # ← 加上这一行
