#### 可乐服务层
# 2026-08-07 14:29


[package]
name = "service"
version.workspace = true
edition.workspace = true

[dependencies]
#### 内部依赖
kits = { path = "../kits" }
network = { path = "../network"}
cola_data = { path = "../cola_data" }
repository = { path = "../repository" }

## 外部依赖
anyhow = "1.0.102"
tracing = "0.1.44"
chrono = "0.4.44"
tokio = "1.52.3"

#### 外部依赖