#### Repo 🔌 适配器 -
# * 将 repository 层的静态函数包装成 cola_data 中定义的 port trait 实现
# 2026-06-12 10:41

[package]
name = "repo_adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
## 内部依赖
cola_data = { path = "../cola_data" }
app_config = { path = "../app" }
port = { path = "../port" }
repository = { path = "../repository" }
service = { path = "../service" }

## 外部依赖
async-trait = "0.1.89"
anyhow = "1.0.99"
tracing = "0.1.44"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono", "macros"] }
chrono = { version = "0.4.42", features = ["serde"] }
rust_decimal = { version = "1.42.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
redis = { version = "1.0.3", features = ["aio", "tokio-comp"] }
aws-config = { version = "1.10.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.140.0", features = ["behavior-version-latest"] }
uuid = { version = "1.23.1", features = ["v4"] }
