#### 可乐动态
# 2026-05-20 01:30

[package]
name = "cola_dynamic"
version = "0.1.0"
edition = "2024"

[dependencies]
#### 内部依赖
#app_core = { path = "../cola_video" }
cola_data = { path = "../cola_data" }
repository = { path = "../repository" }
port = { path = "../port" } ## 服务端口
service = { path = "../service" }  ## 全函数调用service层

#### 外部依赖
async-trait = "0.1.89"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono", "uuid"] }

