#### 可乐IM
## 2026-07-07 14:17


[package]
name = "cola_im"
version.workspace = true
edition.workspace = true

[dependencies]
## 内部依赖
cola_data = { path = "../cola_data" }
cola_music = { path = "../cola_music"}
cola_user = { path = "../cola_user"}
repository = { path = "../repository" }
tracing = "0.1.44"


## 外部依赖
