#### 可乐IM
## 2026-07-07 14:17


[package]
name = "cola_im"
version.workspace = true
edition.workspace = true

[dependencies]
## 内部依赖
cola_data = { path = "../cola_data" }
cola_music = { path = "../cola_music"}
cola_user = { path = "../cola_user"}
port = { path = "../port" } ## 服务端口
repository = { path = "../repository" }
service = { path = "../service" }  ## 全函数调用service层



## 外部依赖
tracing = "0.1.44"